version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run dev

  mongo:
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sml99
      - MONGO_INITDB_ROOT_PASSWORD=r1ndpa55w0rd
