version: '3'
services:
  node-app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongo-db:
