name: Run Tests

on:
  pull_request:
    paths:
      - 'app/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: cd app/backend && yarn install

    - name: Run tests
      run: cd app/backend && yarn test